name: Deploy Frontend to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build / Prepare (Oryx)
        uses: azure/appservice-build@v3
        with:
          platform: 'Node'
          platform-version: '24'  # or 24-lts depending on what you choose
          source-directory: 'frontend'
          output-directory: ''

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-cc'  # replace with the name of the Azure Web App you created
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './frontend'
